#!/bin/bash
check=$(ccutil.py revert)

if [[ $check != "No reverts" ]]; then
    echo $check
    read -p "Don't forget to upload those using up manual --reverts! [enter]" -n 1 -r < /dev/tty
fi;

exit 0
